(defun DEL (N LST)
   (COND ((EQ N 1) (CDR LST))
      (T (CONS (CAR LST)
            (DEL (- N 1) (CDR LST))
         )
      )
   )
)
(defun input ()
    (print "Список:")
    (print LIST)
    (print "Введите место удаления:") 
    (set 'P (read))
    (print "Список после удаления элемента:") 
    (set 'LIST(DEL P LIST )) 
   
    
)
(set 'LIST '(35 15 11 16 45 5 66 8))
(input)